services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_PORT}
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "${ZOOKEEPER_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    hostname: kafka
    ports:
      - ${KAFKA_BROKER}:${KAFKA_BROKER}
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:${ZOOKEEPER_PORT}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_BROKER},PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "${KAFKA_BROKER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic functions --replication-factor 1 --partitions 1
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  postgres:
    build:
      context: ..
      dockerfile: deployments/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT_INCREMENTED}:${POSTGRES_PORT}"
    volumes:
      - godex-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  init-postgres:
    image: postgres:13-alpine
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'Postgres is up - executing initialization script'
      psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /scripts/init-db.sql
      "
    volumes:
      - ../scripts:/scripts

  parser:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: parser
        SERVICE_PORT: ${PARSER_PORT}
    ports:
      - "${PARSER_PORT}:${PARSER_PORT}"
    environment:
      - KAFKA_BROKER_SERV=kafka:${KAFKA_BROKER}
    depends_on:
      kafka:
        condition: service_healthy
    init: true

  container:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: container
        SERVICE_PORT: ${CONTAINER_PORT}
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    environment:
      - KAFKA_BROKER_SERV=kafka:${KAFKA_BROKER}
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    init: true

  gateway:
    build:
      context: ..
      dockerfile: deployments/go/Dockerfile
      args:
        SERVICE_NAME: gateway
        SERVICE_PORT: ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - container
      - parser
    init: true
  
  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
    depends_on:
      - gateway

volumes:
  godex-data: